<a href="https://colab.research.google.com/github/KayalvizhiT513/Eigen-Values-and-Vectors/blob/main/EigenValuesVectors_Notebook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sympy as sp

In [66]:
def replace_small_values(matrix, threshold=1e-10):
    # Create a copy of the input matrix
    new_matrix = np.array(matrix.copy())

    # Replace values with absolute value >= threshold as 0
    new_matrix[np.abs(new_matrix) <= threshold] = 0

    return new_matrix

In [81]:
def eigen_values_vectors(M):
    # Calculate eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(M)

    # Print eigenvalues and eigenvectors
    print("Eigenvalues:", eigenvalues)
    print("Eigenvectors:")

    # Concatenate eigenvectors into a matrix
    eig_matrix = np.column_stack(eigenvectors)
    eig_matrix = replace_small_values(eig_matrix)
    print(eig_matrix)

    np_rank = np.linalg.matrix_rank(eig_matrix)

    eig_matrix_sympy = sp.Matrix(eig_matrix)

    # Compute the reduced row echelon form (RREF)
    rref = eig_matrix_sympy.rref()
    print("RREF:")
    print(rref[0])

    # Find the rank of the matrix
    rank = eig_matrix_sympy.rank()
    print("Rank of the RREF:", rank)

    # Check if eigenvectors are linearly independent
    if rank == min(M.shape):
        print("The eigenvectors corresponding to distinct eigenvalues are linearly independent.")
    else:
        print("The eigenvectors corresponding to distinct eigenvalues are linearly dependent.")


Eigenvectors corresponding to distinct eigenvalues are linearly independent


In [82]:
 # Define the matrix A
A = np.array([[5, 2, 0],
      [2, 5, 0],
      [-3, 4, 6]])
eigen_values_vectors(A)

Eigenvalues: [6. 7. 3.]
Eigenvectors:
[[ 0.          0.          1.        ]
 [ 0.57735027  0.57735027  0.57735027]
 [ 0.36650833 -0.36650833  0.85518611]]
RREF:
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Rank of the RREF: 3
The eigenvectors corresponding to distinct eigenvalues are linearly independent.


In [83]:
# Define the matrix A
A1 = np.array([[2, 1, 0],
               [1, 3, -1],
               [0, -1, 4]])
eigen_values_vectors(A1)

Eigenvalues: [1.26794919 3.         4.73205081]
Eigenvectors:
[[-0.78867513  0.57735027  0.21132487]
 [-0.57735027 -0.57735027 -0.57735027]
 [-0.21132487 -0.57735027  0.78867513]]
RREF:
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Rank of the RREF: 3
The eigenvectors corresponding to distinct eigenvalues are linearly independent.


Two different eigenvectors corresponding to the same eigenvalue are not always linearly dependent

In [84]:
B1 = np.array([[2, 1],
               [0, 2]])
eigen_values_vectors(B1)

Eigenvalues: [2. 2.]
Eigenvectors:
[[ 1.  0.]
 [-1.  0.]]
RREF:
Matrix([[1, 0], [0, 0]])
Rank of the RREF: 1
The eigenvectors corresponding to distinct eigenvalues are linearly dependent.


In [85]:
B2 = np.array([[2, 0],
               [0, 2]])
eigen_values_vectors(B2)

Eigenvalues: [2. 2.]
Eigenvectors:
[[1. 0.]
 [0. 1.]]
RREF:
Matrix([[1, 0], [0, 1]])
Rank of the RREF: 2
The eigenvectors corresponding to distinct eigenvalues are linearly independent.
